before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc) --path vendor/bundle

test:Ruby 2.5:
  image: ruby:2.5
  cache:
    paths:
      - .bundle
      - vendor/bundle
  script:
    - bundle exec rubocop
  tags:
    - docker
  except:
    - tags

release:Ruby 2.5:
  image: ruby:2.5
  cache:
    paths:
      - .bundle
      - vendor/bundle
  script:
    - bundle exec rubocop
    - gem install dpl --no-document
    - find . -type f -exec chmod o--w "{}" \;
    - dpl --provider=rubygems --api-key=$RUBYGEMS_API_KEY --gem=supermarket_sync
  artifacts:
    name: "supermarket_sync-$CI_BUILD_REF_NAME"
    paths:
      - ./*.gem
  tags:
    - docker
  only:
    - tags
