#!/usr/bin/env ruby
# encoding: UTF-8
# Chef Supermarket Sync Utility
# Brian Dwyer - Intelligent Digital Services - 11/7/18

lib = File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib'))
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

# => Catch Ctrl+C's to avoid stack traces
Signal.trap('INT') { abort }

require 'supermarket_sync'

SupermarketSync::CLI.run(ARGV)
