name: Ruby
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    container: ruby:3.0
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Info
        id: git
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Test
        env:
          ABC: '123'
        run: |
          gem install rubocop --no-document
          rubocop

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          ABC: '123'
        run: |
          gem install dpl --no-document
          find . -type f -exec chmod o--w "{}" \;

      - run: dpl --provider=rubygems --api-key=$RUBYGEMS_API_KEY --gem=supermarket_sync
