name: Ruby
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    container: ruby:3.0
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Info
        id: git
        run: |
          echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Test
        env:
          ABC: '123'
        run: |
          gem install rubocop --no-document
          rubocop

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          gem install dpl --no-document
          find . -type f -exec chmod o--w "{}" \;
          dpl --provider=rubygems --api-key=${{ secrets.RUBYGEMS_API_KEY }} --gem=supermarket_sync
